//USER ADMIN
export const GET_LIST_USER = "GET_LIST_USER";
export const UPDATE_USER = "UPDATE_USER";
export const USER_DELETE = "USER_DELETE";
export const EDIT_USER = "EDIT_USER";
export const SEARCH_USER = "SEARCH_USER";
export const ADD_USER = "ADD_USER";

//USER HOMEPAGE
export const GET_BANNER = "GET_BANNER";
export const GET_MOVIELIST = "GET_MOVIELIST";
export const GET_MOVIETAB = "GET_MOVIETAB";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const GET_USER_TICKET = "GET_USER_TICKET";

//USER LOGIN
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";

//USER BOOKING PAGE
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_LIST_SEAT = "GET_LIST_SEAT";
export const CLICK_SEAT = "CLICK_SEAT";
export const BOOK_TICKET_NOW = "BOOK_TICKET_NOW";

//ADMIN MOVIE
export const DELETE_MOVIE = "DELETE_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const UPLOAD_NEWMOVIE = "UPLOAD_NEWMOVIE";
export const MOVIE_EDITING = "MOVIE_EDITING";
//-Add new showtimes
export const GET_THEATRESYSTEM = "GET_THEATRESYSTEM";
export const GET_THEATRE = "GET_THEATRE";
